# Site settings
title: WS Group
lang: pt-BR
email: ws@groupws.com.br
description: >
  Grupo de empresas criado com o objetivo de atender v√°rias das necessidades que um cliente procura no setor de arquitetura.
brand: "#c29d52"

facebook: groupws
instagram: group_ws

collections:
  sections:
    output: false
    title: false
  svg:
    output: false

# Build settings
markdown: kramdown
baseurl: ""
url: "http://groupws.com.br"

defaults:
  - scope:
      path: ""
      type: sections
    values:
      title: nil

plugins:
  - jekyll-coffeescript
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
